services:
  nginx:
    container_name: ${APP_NAME}_nginx
    tty: true
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    depends_on:
      - php
    ports:
      - "80:80"
      - "443:443"
    networks:
      - ${APP_NAME}_network

  php:
    container_name: ${APP_NAME}_php
    tty: true
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - .:/var/www/html
    networks:
      - ${APP_NAME}_network

  postgresql:
    image: postgres
    container_name: ${APP_NAME}_postgresql
    environment:
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: admin
        POSTGRES_DB: laratest
    ports:
        - "5432:5432"
    volumes:
        - laratest_postgresql:/var/lib/mysql
    networks:
        - ${APP_NAME}_network

  redis:
      image: redis:6.2.6-alpine
      container_name: ${APP_NAME}_redis
#      restart: unless-stopped
      networks:
          - ${APP_NAME}_network
      volumes:
          - laratest_redis:/data
      ports:
          - "6379:6379"

volumes:
    laratest_postgresql:
    laratest_redis:


networks:
    laratest_network:
        name:  ${APP_NAME}_network
        driver: bridge
        external: true
